export const filterListByCategory = {
  courseType: ['과목', '챌린지', '테스트'],
  format: ['자유 선택형', '순차 완료형'],
  category: ['프로그래밍 기초', '데이터 분석', '웹', '인공지능', '알고리즘'],
  level: ['입문', '초급', '중급', '고급', '심화'],
  programmingLanguage: [
    'C',
    'C++',
    '자바',
    '파이썬',
    '자바스크립트',
    'R',
    'HTML/CSS',
    'SQL',
    '아두이노',
    '스크래치',
    '코틀린',
    '스위프트',
    '엔트리',
  ],
  price: ['무료', '유료', '구독', '학점'],
};
